name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Show environment
        run: |
          echo "Working directory: $(pwd)"
          node --version
          npm --version
          ls -la

      - name: Install & Build
        run: |
          set -eux  # 実行内容を表示し、エラーで止める
          npm ci --legacy-peer-deps
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_1720D }}
          channelId: live
          projectId: portfolio-1720d
